name: Weekly Lotto Update

on:
  schedule:
    - cron: '30 12 * * 6' # 매주 토요일 UTC 12:30 (한국시간 21:30)
  workflow_dispatch: # 수동 실행 버튼 생성

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests openpyxl pandas beautifulsoup4

      - name: Run update script
        run: python update_lotto.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          echo "Last run: $(date)" > last_run.txt
          
          git add lotto_prob.xlsx last_run.txt
          
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update lotto data ($(date +'%Y-%m-%d %H:%M'))"
            git push origin main
          else
            echo "여전히 변경사항이 없다고 나옵니다."
          fi
